# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Installing Snyk CLI..."
    curl -sL https://snyk.io/cli/install | bash
  displayName: 'Install Snyk CLI'

- script: |
    echo "Verifying Snyk CLI installation..."
    snyk --version
  displayName: 'Verify Snyk CLI Installation'